### ISSUE TITLE
Onboarding for 2022 Steering Committee members

### ISSUE THREAD

**Issue by justaugustus** [todogroup/governance#151]
### Incoming

- Shilla Saebi - @shillasaebi, Comcast
- Stephen Augustus - @justaugustus, Cisco
- Thomas Steenbergen - @tsteenbe, HERE Technologies
- VM (Vicky) Brasseur - @vmbrasseur, Wipro

### Outgoing

- @caniszczyk
- @DuaneOBrien
- @stormypeters
- @kpfleming

## Information to gather or verify

- [x] GitHub ID of any new steering committee member(s) - listed above
- [x] Email address of any new steering committee member(s) - listed in [MEMBERS.csv](https://github.com/todogroup/governance/blob/master/MEMBERS.csv)

### Repo references

- [x] `todogroup/governance`: https://github.com/todogroup/governance/pull/152
  - [x] [`README.md`](https://github.com/todogroup/governance/blob/master/README.md) on the governance repo
  - [x] The SC member list on the [resolution template](https://github.com/todogroup/governance/blob/master/resolutions/template/standard.md)
  - [x] `collaborators` array in [settings.yml](https://github.com/todogroup/governance/blob/master/.github/settings.yml)
  - [x] Update [`EMERITUS.md`
](https://github.com/todogroup/governance/blob/master/EMERITUS.md)
- [x] [`todogroup/todogroup.org`](https://github.com/todogroup/todogroup.org): https://github.com/todogroup/todogroup.org/pull/269

### GitHub teams

- [x] [@todogroup/steering-committee](https://github.com/orgs/todogroup/teams/steering-committee)

### Mailing lists / calendar invites / Slack channels

- [x] The Steering Committee email alias on GSuite (LF staff will need to do this one): https://github.com/todogroup/administration/issues/5
- [x] Invitees on Steering Committee meeting calendar event: https://github.com/todogroup/administration/issues/5
- [x] Add to SC Slack channel: https://github.com/todogroup/administration/issues/5

**Comment by justaugustus** [comment]
The [blog post](https://github.com/todogroup/todogroup.org/pull/270) has merged, so I'm calling this closed.
