### ISSUE TITLE
[ONBOARDING] General Member - Camunda

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#174]
# TODO General Member Onboarding

This is an issue created to onboard new TODO Group General Members.

## Company

Camunda

### Members

- Mary Thengvall (primary)
- Ulrike Liss
- Kiran Oliver

## Contact Information

- [x] For each representative of the General Member company, collect the
      following:
  - name
  - pronouns
  - company email address
  - GitHub username
  - whether or not the representative is the primary contact for the company
- [x] Update the members list to included the collected contact information
  - [x] [administration repo](https://github.com/todogroup/administration/MEMBERS.csv)
  - [x] [governance repo](/MEMBERS.csv)

## Communication channels

Ensure that member representatives have joined the following:

- [x] [TODO Group Slack](https://slack.todogroup.org/)
- [x] [Community Mailing List](https://docs.google.com/forms/d/e/1FAIpQLSeU0YGM_IJ6gY8E5IIiwXKD_FZi3kAVc4E9_-3dtTDyKMSjdA/viewform)

### GitHub

- [x] Invite members to the [`Core` GitHub team](https://github.com/orgs/todogroup/teams/core)
  (this will send them an invite to the GitHub organization and grant them
  access to private repositories)

### Private channels

Add members to the following:

- [x] [General Member mailing list](https://groups.google.com/g/private-todogroup)
- [x] General Member Slack channel: [#private](https://thetodogroup.slack.com/archives/G5TBGTX29)

## Meetings and Calls

Google Groups should automatically invites members to meetings, but ensure that 
they have invites for the following meetings:

- [x] General Members Touchpoint
- [x] General Members AMA session

## Resources and initiatives

- [x] Ensure members are aware of the General Members [onboarding guide](https://github.com/todogroup/governance/blob/main/onboarding/general-member.md)

**Comment by anajsana** [comment]
Hey @UlrikeLiss @mary-grace and @celanthe the onboarding checklist for Camunda is almost done 👍 I will just need @celanthe and @UlrikeLiss to join [TODO slack channel](https://slack.todogroup.org/) so I can add them to the #private general member channel

**Comment by anajsana** [comment]
All done! closing this issue.
