### ISSUE TITLE
[ONBOARDING] General Member - Cisco (additional members)

### ISSUE THREAD

**Issue by justaugustus** [todogroup/governance#178]
# TODO General Member Onboarding

This is an issue created to onboard new TODO Group General Members.

## Company

Cisco

### Members

- @justaugustus (primary)
- @eckelcu
- @riskin

## Contact Information

- [ ] For each representative of the General Member company, collect the
      following:
  - name
  - pronouns
  - company email address
  - GitHub username
  - whether or not the representative is the primary contact for the company
- [ ] Update the members list to included the collected contact information
  - [ ] [administration repo](https://github.com/todogroup/administration/MEMBERS.csv)
  - [ ] [governance repo](https://github.com/todogroup/governance/MEMBERS.csv)

## Communication channels

Ensure that member representatives have joined the following:

- [ ] [TODO Group Slack](https://slack.todogroup.org/)
- [ ] [Community Mailing List](https://docs.google.com/forms/d/e/1FAIpQLSeU0YGM_IJ6gY8E5IIiwXKD_FZi3kAVc4E9_-3dtTDyKMSjdA/viewform)

### GitHub

- [x] Invite members to the [`Core` GitHub team](https://github.com/orgs/todogroup/teams/core)
  (this will send them an invite to the GitHub organization and grant them
  access to private repositories)

### Private channels

Add members to the following:

- [ ] [General Member mailing list](https://groups.google.com/g/private-todogroup)
- [ ] General Member Slack channel: [#private](https://thetodogroup.slack.com/archives/G5TBGTX29)

## Meetings and Calls

Google Groups should automatically invites members to meetings, but ensure that 
they have invites for the following meetings:

- [ ] General Members Touchpoint
- [ ] General Members AMA session

## Resources and initiatives

- [ ] Ensure members are aware of the General Members [onboarding guide](https://github.com/todogroup/governance/blob/main/onboarding/general-member.md)

**Comment by anajsana** [comment]
hey @justaugustus I would need @eckelcu and @riskin email info to give them access. You can share this via slack channel if you want 👍 Also, they can use [this link](https://slack.todogroup.org/) to join the slack and give them access to private

**Comment by eckelcu** [comment]
I was able to join the slack channel and can see 30 repos, or which some are private.
