### ISSUE TITLE
[ONBOARDING] General Member - Cisco (additional members)

### ISSUE THREAD

**Issue by justaugustus** [todogroup/governance#217]
# TODO General Member Onboarding

This is an issue created to onboard new TODO Group General Members.

## Company

Cisco

### Additional members

- @juliaferraioli (affiliation change)
- @detiber

## Contact Information

- [ ] For each representative of the General Member company, collect the
      following:
  - name
  - pronouns
  - company email address
  - GitHub username
  - whether or not the representative is the primary contact for the company
- [ ] Update the members list to included the collected contact information
  - [ ] [administration repo](https://github.com/todogroup/administration/MEMBERS.csv)
  - [ ] [governance repo](/MEMBERS.csv)

## Communication channels

Ensure that member representatives have joined the following:

- [ ] [TODO Group Slack](https://slack.todogroup.org/)
- [ ] [Community Mailing List](https://docs.google.com/forms/d/e/1FAIpQLSeU0YGM_IJ6gY8E5IIiwXKD_FZi3kAVc4E9_-3dtTDyKMSjdA/viewform)

### GitHub

- [ ] Invite members to the [`Core` GitHub team](https://github.com/orgs/todogroup/teams/core)
  (this will send them an invite to the GitHub organization and grant them
  access to private repositories)

### Private channels

Add members to the following:

- [ ] [General Member mailing list](https://groups.google.com/g/private-todogroup)
- [ ] General Member Slack channel: [#private](https://thetodogroup.slack.com/archives/G5TBGTX29)

## Meetings and Calls

Google Groups should automatically invites members to meetings, but ensure that 
they have invites for the following meetings:

- [ ] General Members Touchpoint
- [ ] General Members AMA session

## Resources and initiatives

- [ ] Ensure members are aware of the General Members [onboarding guide](https://github.com/todogroup/governance/blob/main/onboarding/general-member.md)

**Comment by justaugustus** [comment]
@anajsana -- I'll take care of the onboarding items that I have access to action on!

**Comment by detiber** [comment]
Joined slack with the username of `detiber` and joined the mailing list using my corporate email address

**Comment by juliaferraioli** [comment]
In slack with username `juliaferraioli` and already on both mailing lists as well.

**Comment by detiber** [comment]
Just following up, I submitted the form to join the community mailing list, but haven't seen any response. I'm not sure if it's related to the email address I used `jdetiber`at`cisco.com` is connected to a non-functional google account, delays in the moderator queue, or it's being filtered by the corporate mail system.

I can switch to using my personal google account if needed, but would prefer to have things going to my corporate email if at all possible.

Is there someone that I should reach out to to figure out how best to proceed?

**Comment by anajsana** [comment]
> Just following up, I submitted the form to join the community mailing list, but haven't seen any response. I'm not sure if it's related to the email address I used `jdetiber`at`cisco.com` is connected to a non-functional google account, delays in the moderator queue, or it's being filtered by the corporate mail system.
> 
> I can switch to using my personal google account if needed, but would prefer to have things going to my corporate email if at all possible.
> 
> Is there someone that I should reach out to to figure out how best to proceed?

@detiber you should now have access to the Community Mailing List (Sorry, the process is not automatic and I had to add you manually) 🙂 Please let me know if you have any issues!

**Comment by detiber** [comment]
Following up, looks like I'm good to go on both the community mailing list and general member mailing list.

**Comment by detiber** [comment]
@anajsana just to follow up on this, I put in a request to add my person gmail account `detiber`@`gmail` for the community list, and would appreciate it getting added to the general mailing list, since my Cisco account does not have proper access to google Docs for the purposes of the meeting agenda/notes
