### ISSUE TITLE
[Strategic Goal] Create Framework for local TODO gatherings

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#231]
There is interest from the community in having local OSPO informal gatherings (also for non-native English-speaking regions). The SC agreed to build a framework to align these efforts and define common criteria and resources required.

[This g.doc](https://docs.google.com/document/d/1AEGQWQ6KZNBIRu-UFUoOb-bPw2TJvZS4HXn1GeCv3oU/edit?usp=sharing) will work as a draft to build the initial framework version.

**Action Items**

- [x] Framework draft version created
- [x] Framework draft version reviewed by SC
- [x] Framework draft content submitted as PR under OSPOlogy repo
- [x] PR approved and merged

**Comment by anajsana** [comment]
Please SC review the framework draft that you will find in the following [g.doc]([This g.doc](https://docs.google.com/document/d/1AEGQWQ6KZNBIRu-UFUoOb-bPw2TJvZS4HXn1GeCv3oU/edit?usp=sharing)) when you can 👍
