### ISSUE TITLE
[TODO OSPO Ambassador] Request - [INDIVIDUAL NAME]

### ISSUE THREAD

**Issue by Riadne** [todogroup/governance#300]
# TODO OSPO Ambassador Request

This is an issue created to request to become an OSPO Ambassador. If you (as individual) are interested to apply, please make sure you have (1) read the [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)
and (2) fulfil the requirements from the Pre-submission checklist.

## Pre-submission checklist:

- [ ] I am 18 years of age or older
- [ ] I abide the [TODO Code Of Conduct](https://todogroup.org/code-of-conduct/)
- [ ] I abide the [LF antitrust policy](https://www.linuxfoundation.org/legal/antitrust-policy)
- [ ] I Confirm I meet AT LEAST ONE of the criteria documented at [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)

## Contact Information

We would need the following information about you to get in contact if elected:

- Name and Surname
- (Optional) Organization
- TODO Slack username or email
- GitHub or GitLab Handle
- (Optional) Frediverse Handle

## Current involvement in TODO Community

Who are you?

- [ ] An active contributor to a TODO initiative (OSPOlogy, OSPO Landscape, Website, OSPO Book, etc)
- [ ] A representative from a TODO General Member or OSPO Associate organization
- [ ] An OSPO Local Organizer and/or OSPOlogy Organizer
- [ ] An active leader in the TODO community with a minimum of 1 year of experience in:
    * Organizing events (virtual/in-person)
    * Speaking at events
    * Mentoring others 
    * Creating content (e.g., blogs, videos, etc.)

## REQUIRED: What do you expect from TODO Group as an TODO OSPO Ambassador? Whow would you help the community to thrive?

This is a very important section to understand how you would like to help the OSPO Ecosystem and engage in the TODO community. 
Here you can also provide links to resources (blogs on OSPOs, Community calls and/or OSPOlogy live micro-conferences where you participated, etc)
