### ISSUE TITLE
[TODO OSPO Ambassador] Request - Hitomi Mizugaki

### ISSUE THREAD

**Issue by hit0mim** [todogroup/governance#319]
# TODO OSPO Ambassador Request

This is an issue created to request to become an OSPO Ambassador. If you (as individual) are interested to apply, please make sure you have (1) read the [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)
and (2) fulfil the requirements from the Pre-submission checklist.

## Pre-submission checklist:

- [x] I am 18 years of age or older
- [x] I abide the [TODO Code Of Conduct](https://todogroup.org/code-of-conduct/)
- [x] I abide the [LF antitrust policy](https://www.linuxfoundation.org/legal/antitrust-policy)
- [x] I Confirm I meet AT LEAST ONE of the criteria documented at [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)

## Contact Information

We would need the following information about you to get in contact if elected:

- Hitomi Mizugaki
- Cuemby
- hitomi@cuemby.com 
- hit0mim
- (Optional) Frediverse Handle 

## Current involvement in TODO Community

Who are you?

- [ ] An active contributor to a TODO initiative (OSPOlogy, OSPO Landscape, Website, OSPO Book, etc)
- [x] A representative from a TODO General Member or OSPO Associate organization
- [ ] An OSPO Local Organizer and/or OSPOlogy Organizer
- [ ] An active leader in the TODO community with a minimum of 1 year of experience in:
    * Organizing events (virtual/in-person)
    * Speaking at events
    * Mentoring others 
    * Creating content (e.g., blogs, videos, etc.)

## REQUIRED: What do you expect from TODO Group as an TODO OSPO Ambassador? Whow would you help the community to thrive?

As a TODO OSPO Ambassador, I envision leveraging the vibrant movement toward open-source collaboration to foster a culture of continuous learning, innovation, and community engagement. With South Florida's emerging status as a tech hub, my goal is to utilize this unique position to catalyze corporate participation in open-source projects. This effort will begin in my local community, aiming to turn South Florida into a model for open-source contribution and collaboration.

My approach focuses on organizing targeted meetups, mentoring emerging talents, and actively engaging in OSPOlogy meetings to encourage both individuals and organizations to contribute meaningfully to open-source initiatives. Drawing from my experience of establishing a CNCF community group in South Florida and supporting the first KCD Colombia in 2023, I aim to bridge gaps and build a network of open-source enthusiasts and professionals. As a woman and a minority in tech, I am particularly passionate about creating inclusive spaces where traditionally underrepresented groups feel welcomed and empowered to contribute. My expectation from the TODO Group is to support these initiatives, providing platforms and resources that amplify our efforts to cultivate a diverse, collaborative, and innovative open-source community.

**Comment by anajsana** [comment]
Sorry for the slow reply @hit0mim and thank you for your interest in becoming a TODO ambassador!

I'm sending this to the TODO Steering Committe to review durign tomorrow's Steering Committee meeting (Friday 26th) and will get back to you with an answer

**Comment by anajsana** [comment]
Thanks for your patience @hit0mim. The SC has reviewed and approved your submission to join as new TODO Ambassador, congratulations!

### What's next?

Let me share a short to-do checklist here so you can follow up on the onboarding progress. As soon as these items are completed by me, I will mark them as done:

- [ ] Give you write access to the [OSPO Local Meetup LATAM chapter](https://community.linuxfoundation.org/ospo-local-meetup-latam-spanish-speaking/) to create and managage meetups.
- [ ] Added contact information to the ambassador associates page: https://todogroup.org/community/ambassadors/
- [ ] Create blog post announcement in TODO to welcome you as new TODO ambassador: https://todogroup.org/blog/
- [ ]Share the announcement via TODO slack and mailing list
