### ISSUE TITLE
[ONBOARDING]  [Update] General Member - Comcast

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#331]
# TODO General Member Onboarding

This is an issue created to onboard new TODO Group General Members.

## Organization

Comcast

### New Member

- Anu Sha

## Contact Information

- [x] For each representative of the General Member company, collect the
      following:
  - name
  - pronouns
  - company email address
  - GitHub username
  - whether or not the representative is the primary contact for the company
- [x] Update the members list to included the collected contact information at [governance repo](https://github.com/todogroup/governance/blob/main/MEMBERS.csv)

## Communication channels

Ensure that member representatives have joined the following:

- [x] [TODO Group Slack](https://join.slack.com/t/thetodogroup/shared_invite/zt-169ok18cz-Pi6tpVHTeW9254d1FpkLew)
- [x] [Community Mailing List](https://docs.google.com/forms/d/e/1FAIpQLSeU0YGM_IJ6gY8E5IIiwXKD_FZi3kAVc4E9_-3dtTDyKMSjdA/viewform)

### GitHub

- [x] Invite members to the [`Core` GitHub team](https://github.com/orgs/todogroup/teams/core)
  (this will send them an invite to the GitHub organization and grant them
  access to private repositories)

### Private channels

Add members to the following:

- [x] [General Member mailing list](https://groups.google.com/g/private-todogroup)
- [x] General Member Slack channel: [#private](https://thetodogroup.slack.com/archives/G5TBGTX29)

## Meetings and Calls

Google Groups should automatically invites members to meetings, but ensure that 
they have invites for the following meetings:

- [x] General Members Touchpoint

## Resources and initiatives

- [x] Ensure members are aware of the General Members [onboarding guide](https://github.com/todogroup/governance/blob/main/onboarding/general-member.md)

**Comment by Anu1025sha** [comment]
name - Anusha Pavuluri
    pronouns- She/Her
    company email address - anusha_pavuluri@comcast.com
    GitHub username - anu1025sha
    whether or not the representative is the primary contact for the company - No

**Comment by anajsana** [comment]
Thanks for the info @Anu1025sha ! I've given you access to the general member ML with your Gmail email since the Comcast one was giving me an error when adding you to the list. I've also sent you and invite via noreply@github.com that you would need to accept within 10 days to add you as a member of the core team in the TODO Group GitHub organization.

**Comment by anajsana** [comment]
You can join the community mailing list here: https://lists.todogroup.org/g/community
