### ISSUE TITLE
[TODO OSPO Ambassador] Request - Fernando Eugenio Correa

### ISSUE THREAD

**Issue by fer-correa** [todogroup/governance#338]
# TODO OSPO Ambassador Request

This is an issue created to request to become an OSPO Ambassador. If you (as individual) are interested to apply, please make sure you have (1) read the [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)
and (2) fulfil the requirements from the Pre-submission checklist.

## Pre-submission checklist:

- [x] I am 18 years of age or older
- [x] I abide the [TODO Code Of Conduct](https://todogroup.org/code-of-conduct/)
- [x] I abide the [LF antitrust policy](https://www.linuxfoundation.org/legal/antitrust-policy)
- [x] I Confirm I meet AT LEAST ONE of the criteria documented at [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)

## Contact Information

We would need the following information about you to get in contact if elected:

- Fernando Eugenio Correa
- Mercado Libre (MELI)
- fernando.correa@mercadolivre.com
- fer-correa
- fercorrea@mastodon.social

## Current involvement in TODO Community

Who are you?

- [ ] An active contributor to a TODO initiative (OSPOlogy, OSPO Landscape, Website, OSPO Book, etc)
- [ ] A representative from a TODO General Member or OSPO Associate organization
- [x] An OSPO Local Organizer and/or OSPOlogy Organizer
- [ ] An active leader in the TODO community with a minimum of 1 year of experience in:
    * Organizing events (virtual/in-person)
    * Speaking at events
    * Mentoring others 
    * Creating content (e.g., blogs, videos, etc.)

## MANDATORY: What do you expect from Grupo TODO as a TODO OSPO Ambassador? How would you help the community thrive?

Since I joined MELI in 2021 and joined the initiative that 2 years ago officially became the company's OSPO, I noticed a big gap between what Open Source is (culture, community, innovation, technology, inclusion, etc.) to how is still seen in LATAM. Thanks to much of the material made available by the TODO Group, we did not leave ZERO, but we still had the management know that this was something important to be worked on within the company. MELI is a company that operates in several countries in Latin America and, with contact with these different cultures, we detected that education/training work would be important because the culture of the region is seen as seeking shortcuts, having different characteristics of European, Asian or from the United States and Canada.
My main focus today has been on working hard to generate as much material and content as possible to train and educate people in the region, always focusing on the content having versions in the main languages ​​of the region, since mainly the compliance part of Licenses are often seen as something tiring and very complex, if we generate the content more clearly and in the native language, it will give us a better result.
As a Brazilian who has a lot of contact with people from different countries in the region (in my day-to-day work) I see a great opportunity to add voices from the region to reach more people and organizations.
I have been participating strongly with some members of InnerSource Commons (mainly Yuki Hatori , working with him is incredible) to also create a strong innersource community in Brazil, initially, and later in the region. We already have our seed sprouting in this particular case.
I see great potential in the region, but at the same time a certain resistance, and as I said before, I have a great interest in providing as many people with knowledge to help them have an OSPO in their organizations and also participate in projects and the community in general .

**Comment by anajsana** [comment]
Thank you @fer-correa  for your interest in becoming a TODO Ambassador! Your submission has been shared with our Steering Committee for review 🙂 Please allow up to 10-12 business days for the Steering Committee to give input 🙏

**Comment by anajsana** [comment]
@fer-correa, on behalf of the TODO SC, they would like to learn more about your contributions to TODO. Could you please share any PRs, events you’ve participated in, or other activities or documentation you’ve been involved with in the community? If you have links, feel free to include them, along with a brief description. This information will help SC members make an informed decision regarding your proposal. Thanks!

**Comment by fer-correa** [comment]
Perfect @anajsana ,

Thank you very much for the opportunity.

I will provide a brief introduction that may help you better understand the focus of my contributions to the community.

I am from Brazil and currently part of the OSPO at MELI (Mercado Libre), which operates in much of Latin America (LATAM). Since I began my professional involvement with open source, directly participating in an open-source initiative (later renamed OSPO, largely thanks to what we learned from much of the material generated by TODO Group), I have identified a certain deficiency in the way open-source culture is understood and assimilated when viewed from a Latin American cultural perspective.

My primary focus is to develop the community and its culture in the region, leveraging the advantage of experiencing the region's realities, challenges, and needs.

Below I share some points that I see as important but I want to focus better on contributing to TODO and DevRel Foundation during 2025 in particular.

- OSPO LATAM Meetups: [OSPO @ Latam - Mercado Libre's journey](https://community.linuxfoundation.org/events/details/lfhq-ospo-latam-meetups-presents-ospo-latam-mercado-libres-journey/) | [YOUTUBE : OSPO @ Latam - Mercado Libre's journey](https://www.youtube.com/live/ZV-K7In0qao?si=p0AdFr6yywyCU3Le)
- [KubeDay Colombia 2024 : Embracing Open Source as a Source of Inspiration for Innovation and Collaboration] (https://youtu.be/91Oq6l0jreQ?si=8ZU_ubEcYnM9IkJ8)
- [Cuemby podcast : Del Código al Conocimiento: La Trayectoria de un Ingeniero en Data Science y Open Source | Cap.18] (https://youtu.be/xW_3G1wSnCY?si=IDnYH6g4MMbPyrSQ)
- [InnerSourceLearningPath](https://github.com/InnerSourceCommons/InnerSourceLearningPath/commits?author=fer-correa)
- [innersourcecommons.org](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/553)
- [TODOGroup - ospodefinition.org](https://github.com/todogroup/ospodefinition.org/pull/9#pullrequestreview-1451212251)
- Academic:
Universidad de la Sabana (Colombia) : Open Source, Innersource, Foundations and OSPOs
FGV Brasil : MELI + FGV - Clínica Jurídica (OSPO, GenAI, Intellectual Property and Data Privacy)

**Comment by natalisucks** [comment]
i can see that myslef and @ashleywolf have voted but this doesn't seem to be recorded by the bot – @anajsana FYI

**Comment by fer-correa** [comment]
@natalisucks , your vote has been counted now 👍, thanks.

only the votes from the reactions [here on **Vote created**](https://github.com/todogroup/governance/issues/338#issuecomment-2587164368) are counted (and I can't see @ashleywolf reaction/vote there).

**Comment by fer-correa** [comment]
Hi @anajsana ,
I would like to known about the possibility of a new vote. I am aware that everyone is too busy to take this process again, but my motivation for the request is because in theory the number of votes needed could have been reached given that there was a reaction from Ashley, [here](https://github.com/todogroup/governance/issues/338#issuecomment-2599585616), that unfortunately was not in the comment that considered the vote valid.
I would like to thank you in advance for your attention and the votes/support/reactions received.

**Comment by anajsana** [comment]
> Hi [@anajsana](https://github.com/anajsana) , I would like to known about the possibility of a new vote. I am aware that everyone is too busy to take this process again, but my motivation for the request is because in theory the number of votes needed could have been reached given that there was a reaction from Ashley, [here](https://github.com/todogroup/governance/issues/338#issuecomment-2599585616), that unfortunately was not in the comment that considered the vote valid. I would like to thank you in advance for your attention and the votes/support/reactions received.

Hello Fernando! On behalf of the SC, we wanted to clarify that the poll closing does not mean your proposal was declined. It simply closed automatically after some time because not all members had voted. We plan to reopen the poll this week and will ask SC members to cast their votes before the end of the week to reach a final resolution.

Thank you so much for all your hard work and dedication! We truly appreciate your contributions to the community 🙂

**Comment by ar4mirez** [comment]
I know my vote is non-binding, but I’d like to share that Fernando has been a great support for our efforts in LatAm, and it would be amazing to have an even more supportive community with a fellow ambassador like him. Good luck in the next round, Fer.

**Comment by anajsana** [comment]
> I know my vote is non-binding, but I’d like to share that Fernando has been a great support for our efforts in LatAm, and it would be amazing to have an even more supportive community with a fellow ambassador like him. Good luck in the next round, Fer.

Also for SC members to know: Fernando has been leading with Alice OSPO Book edition and review efforts recently this year and attending Touchpoint calls to give updates about the working group progress

**Comment by anajsana** [comment]
Congrats @fer-correa  ! The vote has passed, and you are officially an OSPO Ambassador

Your term starts today, Wednesday, April 9th, 2025, and will end on Wednesday, April 9th, 2027. You can request to renew your term at that time. Please allow a few days for us to complete your onboarding as an OSPO Ambassador. This includes a blog announcement on TODO and adding your profile to the Ambassador page on the TODO website.

**Comment by fer-correa** [comment]
Thanks @anajsana and @ar4mirez for your support. And to the members of the committee for voting and approval.

Yeah!! "_Let's grow our beloved LATAM community!_" 🚀
