### ISSUE TITLE
[TODO OSPO Ambassador] Request - [INDIVIDUAL NAME]

### ISSUE THREAD

**Issue by harmonyelendu** [todogroup/governance#354]
# TODO OSPO Ambassador Request

This is an issue created to request to become an OSPO Ambassador. If you (as individual) are interested to apply, please make sure you have (1) read the [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)
and (2) fulfil the requirements from the Pre-submission checklist.

## Pre-submission checklist:

- [x] I am 18 years of age or older
- [x] I abide the [TODO Code Of Conduct](https://todogroup.org/code-of-conduct/)
- [x] I abide the [LF antitrust policy](https://www.linuxfoundation.org/legal/antitrust-policy)
- [x] I Confirm I meet AT LEAST ONE of the criteria documented at [TODO OSPO Ambassador Program documentation](https://github.com/todogroup/governance/blob/main/TODO-OSPO-Ambassador-Program.md)

## Contact Information

We would need the following information about you to get in contact if elected:

- Name and Surname: Harmony Elendu 
- (Optional) Organization
- TODO Slack username or email: Harmony Elendu
- GitHub or GitLab Handle: harmonyelendu
- (Optional) Frediverse Handle

## Current involvement in TODO Community

Who are you?

- [x] An active contributor to a TODO initiative (OSPOlogy, OSPO Landscape, Website, OSPO Book, etc)
- [ ] A representative from a TODO General Member or OSPO Associate organization
- [ ] An OSPO Local Organizer and/or OSPOlogy Organizer
- [x] An active leader in the TODO community with a minimum of 1 year of experience in:
    * Organizing events (virtual/in-person)
    * Speaking at events
    * Mentoring others 
    * Creating content (e.g., blogs, videos, etc.)

## REQUIRED: What do you expect from TODO Group as an TODO OSPO Ambassador? Whow would you help the community to thrive?

My involvement in Open Source has centered around awareness, education, and diversity, merged with my skills in documentation, project management, and program management. I have made significant contributions to GNOME and CHAOSS, leading the Technical Writer's Focus Group, co-producing and hosting CHAOSScast, and contributing to various working groups and projects through documentation and project management.

Inspired by the remarkable work of TODO members, I aim to utilize my skill set honed over half a decade to bridge gaps within the community, OSPOs education, and awareness in general, starting on my continent. As an ambassador based in Africa, I will focus on educating and raising awareness among organisations, communities, and talents about TODO's work, the value of OSPOs, and Open Source in general. I will achieve this through meetups, conferences, seminars, educational resources and more while serving as one of the primary contact for African Continent expansion and involvement. I look forward to collaborating with fellow ambassadors and the broader community to achieve our objectives and more.

**Comment by anajsana** [comment]
Thank you @harmonyelendu for your interest in becoming a TODO Ambassador! Your submission has been shared with our Steering Committee for review 🙂 Please allow up to 10-12 business days for the Steering Committee to give input 🙏

**Comment by harmonyelendu** [comment]
Awesome! Will be looking forward to it, many thanks.
